services:
  redis:
    image: redis
    hostname: redis
    container_name: redis
    restart: always
    environment:
      - TZ=Asia/Seoul
    ports:
      - 6379:6379
    networks:
      - default
    command: redis-server